[build]
  publish = "site/public"
  command = "hugo -s site"

[build.environment]
  HUGO_VERSION = "0.142.0"

[context.production]
  command = "hugo -s site"

[context.deploy-preview]
  command = "hugo -s site -b $DEPLOY_PRIME_URL"
